-- MySQL Script generated by MySQL Workbench
-- Sun May  9 14:42:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema irondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema irondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `irondb` DEFAULT CHARACTER SET utf8 ;
USE `irondb` ;

-- -----------------------------------------------------
-- Table `irondb`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`modulo` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `modulo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`rol` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`ventana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`ventana` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `ventana` VARCHAR(45) NULL DEFAULT NULL,
  `codModulo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_ventana_modulo_idx` (`codModulo` ASC),
  CONSTRAINT `fk_ventana_modulo`
    FOREIGN KEY (`codModulo`)
    REFERENCES `irondb`.`modulo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`acceso` (
  `idAcceso` INT(11) NOT NULL AUTO_INCREMENT,
  `codRol` INT(11) NULL DEFAULT NULL,
  `codModulo` INT(11) NULL DEFAULT NULL,
  `codVentana` INT(11) NULL DEFAULT NULL,
  `acceso` INT(11) NULL DEFAULT '0',
  `nuevo` INT(11) NULL DEFAULT '0',
  `actualizar` INT(11) NULL DEFAULT '0',
  `borrar` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`idAcceso`),
  INDEX `fk_acceso_rol_idx` (`codRol` ASC),
  INDEX `fk_acceso_modulo_idx` (`codModulo` ASC),
  INDEX `fk_acceso_ventana_idx` (`codVentana` ASC),
  CONSTRAINT `fk_acceso_modulo`
    FOREIGN KEY (`codModulo`)
    REFERENCES `irondb`.`modulo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acceso_rol`
    FOREIGN KEY (`codRol`)
    REFERENCES `irondb`.`rol` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acceso_ventana`
    FOREIGN KEY (`codVentana`)
    REFERENCES `irondb`.`ventana` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`ajustecolores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`ajustecolores` (
  `nimbusBase` VARCHAR(15) NOT NULL DEFAULT '41,128,185',
  `control` VARCHAR(15) NULL DEFAULT '247,249,249',
  `text` VARCHAR(15) NULL DEFAULT '0,102,153',
  `textfielBackgroung` VARCHAR(15) NULL DEFAULT '255,255,255',
  `textfieldForegroung` VARCHAR(15) NULL DEFAULT '0,0,0')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`anulacioncompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`anulacioncompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codCompra` INT(11) NULL DEFAULT NULL,
  `codMotivo` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `cosUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`anulacionordencompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`anulacionordencompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codOrdenCompra` INT(11) NULL DEFAULT NULL,
  `codMotivo` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `cosUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`anulacionventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`anulacionventa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codVenta` INT(11) NULL DEFAULT NULL,
  `codMotivo` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `cosUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`grupo` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`marca` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`unidadmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`unidadmedida` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `unidadMedida` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`articulo` (
  `codigo` INT(11) NOT NULL,
  `CIP` VARCHAR(25) NULL DEFAULT NULL COMMENT 'codigo interno del producto',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `especificacion` TEXT NULL DEFAULT NULL,
  `fechaIngreso` DATE NULL DEFAULT NULL,
  `precioCosto` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioVenta` DECIMAL(10,2) NULL DEFAULT NULL,
  `codMarca` INT(11) NULL DEFAULT NULL,
  `codFamilia` INT(11) NULL DEFAULT NULL COMMENT 'unidad de medida',
  `codUnidadMedida` INT(11) NULL DEFAULT NULL,
  `impuesto` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_articulo_marca_idx` (`codMarca` ASC),
  INDEX `fk_articulo_familia_idx` (`codFamilia` ASC),
  INDEX `fk_articulo_unidadMedida` (`codUnidadMedida` ASC),
  CONSTRAINT `fk_articulo_familia`
    FOREIGN KEY (`codFamilia`)
    REFERENCES `irondb`.`grupo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_marca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `irondb`.`marca` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_unidadMedida`
    FOREIGN KEY (`codUnidadMedida`)
    REFERENCES `irondb`.`unidadmedida` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`motivobajapersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`motivobajapersonal` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`barrio` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `barrio` VARCHAR(45) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`ciudad` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`departamento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`empresa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Ruc` VARCHAR(10) NULL DEFAULT NULL,
  `Representante` VARCHAR(65) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`establecimiento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `sucursal` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `codEmpresa` INT(11) NULL DEFAULT NULL,
  `codDpto` INT(11) NULL DEFAULT NULL,
  `codCiudad` INT(11) NULL DEFAULT NULL,
  `codBarrio` INT(11) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`),
  INDEX `fk_sucursal_empresa_idx` (`codEmpresa` ASC),
  INDEX `fk_establecimiento_dpto_idx` (`codDpto` ASC),
  INDEX `fk_establecimiento_ciudad_idx` (`codCiudad` ASC),
  INDEX `fk_establecimiento_barrio_idx` (`codBarrio` ASC),
  CONSTRAINT `fk_Establecimiento_empresa`
    FOREIGN KEY (`codEmpresa`)
    REFERENCES `irondb`.`empresa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establecimiento_barrio`
    FOREIGN KEY (`codBarrio`)
    REFERENCES `irondb`.`barrio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establecimiento_ciudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `irondb`.`ciudad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establecimiento_dpto`
    FOREIGN KEY (`codDpto`)
    REFERENCES `irondb`.`departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`personal` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaIngreso` DATE NULL DEFAULT NULL,
  `ci` VARCHAR(45) NULL DEFAULT NULL,
  `primerNombre` VARCHAR(45) NULL DEFAULT NULL,
  `segundoNombre` VARCHAR(45) NULL DEFAULT NULL,
  `apePaterno` VARCHAR(45) NULL DEFAULT NULL,
  `apeMaterno` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNac` DATE NULL DEFAULT NULL,
  `sexo` ENUM('M', 'F') NULL DEFAULT NULL,
  `estadoCivil` ENUM('C', 'S', 'D', 'V') NULL DEFAULT NULL,
  `codDepartamento` INT(11) NULL DEFAULT NULL,
  `codCiudad` INT(11) NULL DEFAULT NULL,
  `codBarrio` INT(11) NULL DEFAULT NULL,
  `casaNro` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `estado` ENUM('A', 'B') NULL DEFAULT 'A' COMMENT 'A - Activo\nB- Dado de baja',
  PRIMARY KEY (`codigo`),
  INDEX `fk_personal_dpto_idx` (`codDepartamento` ASC),
  INDEX `fk_personal_ciudad_idx` (`codCiudad` ASC),
  INDEX `fk_personal_barrio_idx` (`codBarrio` ASC),
  INDEX `fk_personal_establecimiento_idx` (`codSucursal` ASC),
  CONSTRAINT `fk_personal_barrio`
    FOREIGN KEY (`codBarrio`)
    REFERENCES `irondb`.`barrio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_ciudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `irondb`.`ciudad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_dpto`
    FOREIGN KEY (`codDepartamento`)
    REFERENCES `irondb`.`departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_establecimiento`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`usuario` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codPersonal` INT(11) NULL DEFAULT NULL,
  `codRol` INT(11) NULL DEFAULT NULL COMMENT 'nivel de acceso',
  `Login` VARCHAR(20) NULL DEFAULT NULL,
  `Clave` VARCHAR(45) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`),
  INDEX `fk_usuario_rol_idx` (`codRol` ASC),
  INDEX `fk_usuario_personal_idx` (`codPersonal` ASC),
  CONSTRAINT `fk_usuario_personal`
    FOREIGN KEY (`codPersonal`)
    REFERENCES `irondb`.`personal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`codRol`)
    REFERENCES `irondb`.`rol` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`bajapersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`bajapersonal` (
  `codigo` INT NOT NULL,
  `FechaSalida` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codPersonal` INT NULL DEFAULT NULL,
  `codMotivo` INT NULL DEFAULT NULL,
  `codusuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_baja_motivo_idx` (`codMotivo` ASC),
  INDEX `fk_baja_usuario_idx` (`codusuario` ASC),
  INDEX `fk_baja_personal_idx` (`codPersonal` ASC),
  CONSTRAINT `fk_baja_motivo`
    FOREIGN KEY (`codMotivo`)
    REFERENCES `irondb`.`motivobajapersonal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baja_usuario`
    FOREIGN KEY (`codusuario`)
    REFERENCES `irondb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baja_personal`
    FOREIGN KEY (`codPersonal`)
    REFERENCES `irondb`.`personal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`cliente` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `ruc_ci` VARCHAR(12) NOT NULL,
  `primerNombre` VARCHAR(45) NULL DEFAULT NULL,
  `SegundoNombre` VARCHAR(45) NULL DEFAULT NULL,
  `apePaterno` VARCHAR(45) NULL DEFAULT NULL,
  `apeMaterno` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNac` DATE NULL DEFAULT NULL,
  `sexo` ENUM('M', 'F') NULL DEFAULT NULL,
  `estadoCivil` ENUM('S', 'C', 'D', 'V') NULL DEFAULT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `codDepartamento` INT(11) NULL DEFAULT NULL,
  `codCiudad` INT(11) NULL DEFAULT NULL,
  `codBarrio` INT(11) NULL DEFAULT NULL,
  `obs` TEXT NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cliente_dpto_idx` (`codDepartamento` ASC),
  INDEX `fk_cliente_ciudad_idx` (`codCiudad` ASC),
  INDEX `fk_cliente_barrio_idx` (`codBarrio` ASC),
  INDEX `fk_clinte_sucursal_idx` (`codSucursal` ASC),
  CONSTRAINT `fk_cliente_barrio`
    FOREIGN KEY (`codBarrio`)
    REFERENCES `irondb`.`barrio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_ciudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `irondb`.`ciudad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_dpto`
    FOREIGN KEY (`codDepartamento`)
    REFERENCES `irondb`.`departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_establecimiento`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`proveedor` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(10) NULL DEFAULT NULL,
  `razonSocial` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `codBarrio` INT(11) NULL DEFAULT NULL,
  `codCiudad` INT(11) NULL DEFAULT NULL,
  `codDpto` INT(11) NULL DEFAULT NULL,
  `Responsable` VARCHAR(60) NULL DEFAULT NULL,
  `alta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`),
  INDEX `fk_proveedor_barrrio_idx` (`codBarrio` ASC),
  INDEX `fk_proveedor_ciudad_idx` (`codCiudad` ASC),
  INDEX `fk_proveedor_dpto_idx` (`codDpto` ASC),
  CONSTRAINT `fk_proveedor_barrrio`
    FOREIGN KEY (`codBarrio`)
    REFERENCES `irondb`.`barrio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_ciudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `irondb`.`ciudad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_dpto`
    FOREIGN KEY (`codDpto`)
    REFERENCES `irondb`.`departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`ordencompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`ordencompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codProveedor` INT(11) NULL DEFAULT NULL,
  `codUsuario` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `Estado` ENUM('A', 'F') NULL DEFAULT NULL COMMENT 'A: Estado aprobado del documento\nF: El documento ha sido facturado',
  PRIMARY KEY (`codigo`),
  INDEX `fk_orden_sucursal_idx` (`codSucursal` ASC),
  INDEX `fk_orden_usuario_idx` (`codUsuario` ASC),
  INDEX `fk_orden_proveedor_idx` (`codProveedor` ASC),
  CONSTRAINT `fk_orden_proveedor`
    FOREIGN KEY (`codProveedor`)
    REFERENCES `irondb`.`proveedor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_sucursal`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_usuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `irondb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`compra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codOrdenCompra` INT(11) NULL DEFAULT NULL,
  `factura` VARCHAR(15) NULL DEFAULT NULL,
  `codProveedor` INT(11) NULL DEFAULT NULL,
  `codUsuario` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `Estado` ENUM('A', 'N', 'P') NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_compra_proveedor_idx` (`codProveedor` ASC),
  INDEX `fk_compra_usuario_idx` (`codUsuario` ASC),
  INDEX `fk_compra_sucursal_idx` (`codSucursal` ASC),
  INDEX `fk_compra_orden_idx` (`codOrdenCompra` ASC),
  CONSTRAINT `fk_compra_orden`
    FOREIGN KEY (`codOrdenCompra`)
    REFERENCES `irondb`.`ordencompra` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_proveedor`
    FOREIGN KEY (`codProveedor`)
    REFERENCES `irondb`.`proveedor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_sucursal`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_usuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `irondb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`detallecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`detallecompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codArticulo` INT(11) NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioBruto` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoIva` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioNeto` DECIMAL(10,2) NULL DEFAULT NULL,
  `subTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `codCompra` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_detalle_compra_idx` (`codCompra` ASC),
  CONSTRAINT `fk_detalle_compra`
    FOREIGN KEY (`codCompra`)
    REFERENCES `irondb`.`compra` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`detalleordencompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`detalleordencompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codArticulo` INT(11) NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioBruto` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoIva` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioNeto` DECIMAL(10,2) NULL DEFAULT NULL,
  `subTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `codOrdenCompra` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_detalle_compra_idx` (`codOrdenCompra` ASC),
  CONSTRAINT `fk_detalleOrde_ordenCompra`
    FOREIGN KEY (`codOrdenCompra`)
    REFERENCES `irondb`.`ordencompra` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`presupuesto` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codCliente` INT(11) NULL DEFAULT NULL,
  `codUsuario` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `Estado` ENUM('A', 'N') NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_presupuesto_sucursal_idx` (`codSucursal` ASC),
  INDEX `fk_presupuesto_usuario_idx` (`codUsuario` ASC),
  INDEX `fk_presupuesto_cliente_idx` (`codCliente` ASC),
  CONSTRAINT `fk_presupuesto_cliente`
    FOREIGN KEY (`codCliente`)
    REFERENCES `irondb`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presupuesto_sucursal`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presupuesto_usuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `irondb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`detallepresupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`detallepresupuesto` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codArticulo` VARCHAR(10) NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioBruto` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoIva` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioNeto` DECIMAL(10,2) NULL DEFAULT NULL,
  `subTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `codPresupuesto` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_detallePresupuesto_presupuesto_idx` (`codPresupuesto` ASC),
  CONSTRAINT `fk_detallePresupuesto_presupuesto`
    FOREIGN KEY (`codPresupuesto`)
    REFERENCES `irondb`.`presupuesto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`venta` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nroComprobante` VARCHAR(10) NULL DEFAULT NULL,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codCliente` INT(11) NULL DEFAULT NULL,
  `codUsuario` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `Estado` ENUM('A', 'N', 'P') NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_venta_sucursal_idx` (`codSucursal` ASC),
  INDEX `fk_venta_usuario_idx` (`codUsuario` ASC),
  INDEX `fk_venta_cliente_idx` (`codCliente` ASC),
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`codCliente`)
    REFERENCES `irondb`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_sucursal`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `irondb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`detalleventa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codArticulo` INT(11) NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioBruto` DECIMAL(10,2) NULL DEFAULT NULL,
  `montoIva` DECIMAL(10,2) NULL DEFAULT NULL,
  `precioNeto` DECIMAL(10,2) NULL DEFAULT NULL,
  `subTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `codVenta` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_detalleVenta_venta_idx` (`codVenta` ASC),
  CONSTRAINT `fk_detalleVenta_venta`
    FOREIGN KEY (`codVenta`)
    REFERENCES `irondb`.`venta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`facturaventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`facturaventa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaImpresion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codUsuario` INT(11) NULL DEFAULT NULL,
  `codVenta` VARCHAR(45) NULL DEFAULT NULL,
  `estado` ENUM('A', 'N') NULL DEFAULT NULL COMMENT 'Este campo se encarga de alamcenar el estado del documento impreso\nestado N : significa que se anuló el docuemnto\nestado A: signica que el documento está activo',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`motivo` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` ENUM('I', 'E') NULL DEFAULT NULL COMMENT 'I: Movimiento tipo Ingreso\nE: Movimiento tipo egreso',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`flujocaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`flujocaja` (
  `idMovCaja` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `referencia` INT(11) NULL DEFAULT NULL,
  `importe` DECIMAL(10,2) NULL DEFAULT NULL,
  `CodUsuario` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `codMotivo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idMovCaja`),
  INDEX `fk_Caja_establecimiento_idx` (`codSucursal` ASC),
  INDEX `fk_Caja_usuario_idx` (`CodUsuario` ASC),
  INDEX `fk_caja_motivo_idx` (`codMotivo` ASC),
  CONSTRAINT `fk_Caja_establecimiento`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_usuario`
    FOREIGN KEY (`CodUsuario`)
    REFERENCES `irondb`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caja_motivo`
    FOREIGN KEY (`codMotivo`)
    REFERENCES `irondb`.`motivo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`inventario` (
  `idInventario` INT(11) NOT NULL AUTO_INCREMENT,
  `codArticulo` INT(11) NULL DEFAULT NULL,
  `codSucursal` INT(11) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_inventario_establecimiento_idx` (`codSucursal` ASC),
  INDEX `fk_inventario_articulo_idx` (`codArticulo` ASC),
  CONSTRAINT `fk_inventario_articulo`
    FOREIGN KEY (`codArticulo`)
    REFERENCES `irondb`.`articulo` (`codMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_establecimiento`
    FOREIGN KEY (`codSucursal`)
    REFERENCES `irondb`.`establecimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`motivoanulacioncompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`motivoanulacioncompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`motivoanulacionordencompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`motivoanulacionordencompra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`motivoanulacionventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`motivoanulacionventa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`motivomovinventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`motivomovinventario` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivoMovInventario` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` ENUM('E', 'S') NULL DEFAULT NULL,
  `isDefault` INT(1) NULL DEFAULT NULL COMMENT '1 = predefinido\n2 = nuevo',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`movimiento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `codUsuario` INT(11) NOT NULL,
  `codSucursal` INT(11) NOT NULL,
  `codMotivo` INT(11) NOT NULL,
  `codArticulo` INT(11) NULL DEFAULT NULL COMMENT 'precio de costo.',
  `cantAnterior` INT(11) NULL DEFAULT NULL,
  `valorUnitario` DECIMAL(10,2) NULL DEFAULT NULL,
  `valorTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `entrada` INT(11) NULL DEFAULT NULL,
  `salida` INT(11) NULL DEFAULT NULL,
  `cantActual` INT(11) NULL DEFAULT NULL,
  `codCompra` INT(11) NULL DEFAULT NULL,
  `codVenta` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irondb`.`stockminimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irondb`.`stockminimo` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `codGrupo` INT(11) NULL DEFAULT NULL,
  `minimo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
